export const movies = [{
    adult: false,
    backdrop_path: '/sRLC052ieEzkQs9dEtPMfFxYkej.jpg',
    genre_ids: [ 878 ],
    id: 848326,
    original_language: 'en',
    original_title: 'Rebel Moon - Part One: A Child of Fire',
    overview: 'When a peaceful colony on the edge of the galaxy finds itself threatened by the armies of the tyrannical Regent Balisarius, they dispatch Kora, a young woman with a mysterious past, to seek out warriors from neighboring planets to help them take a stand.',
    popularity: 2535.152,
    poster_path: '/ui4DrH1cKk2vkHshcUcGt2lKxCm.jpg',
    release_date: '2023-12-15',
    title: 'Rebel Moon - Part One: A Child of Fire',
    video: false,
    vote_average: 6.456,
    vote_count: 687
  },
  {
    adult: false,
    backdrop_path: '/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg',
    genre_ids: [ 18, 878, 28 ],
    id: 695721,
    original_language: 'en',
    original_title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
    overview: '64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.',
    popularity: 2380.849,
    poster_path: '/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg',
    release_date: '2023-11-15',
    title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
    video: false,
    vote_average: 7.231,
    vote_count: 1150
  },
  {
    adult: false,
    backdrop_path: '/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg',
    genre_ids: [ 28, 12, 14 ],
    id: 572802,
    original_language: 'en',
    original_title: 'Aquaman and the Lost Kingdom',
    overview: "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1863.834,
    poster_path: '/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg',
    release_date: '2023-12-20',
    title: 'Aquaman and the Lost Kingdom',
    video: false,
    vote_average: 6.508,
    vote_count: 265
  },
  {
    adult: false,
    backdrop_path: '/gg4zZoTggZmpAQ32qIrP5dtnkEZ.jpg',
    genre_ids: [ 28, 80 ],
    id: 891699,
    original_language: 'en',
    original_title: 'Silent Night',
    overview: "A tormented father witnesses his young son die when caught in a gang's crossfire on Christmas Eve. While recovering from a wound that costs him his voice, he makes vengeance his life's mission and embarks on a punishing training regimen in order to avenge his son's death.",
    popularity: 1371.218,
    poster_path: '/tlcuhdNMKNGEVpGqBZrAaOOf1A6.jpg',
    release_date: '2023-11-30',
    title: 'Silent Night',
    video: false,
    vote_average: 5.861,
    vote_count: 169
  },
  {
    adult: false,
    backdrop_path: '/r9bIkU9nXZUWSlDUgDMUcDrlK0A.jpg',
    genre_ids: [ 28, 35 ],
    id: 1029575,
    original_language: 'en',
    original_title: 'The Family Plan',
    overview: "Dan Morgan is many things: a devoted husband, a loving father, a celebrated car salesman. He's also a former assassin. And when his past catches up to his present, he's forced to take his unsuspecting family on a road trip unlike any other.",
    popularity: 1292.5,
    poster_path: '/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg',
    release_date: '2023-12-14',
    title: 'The Family Plan',
    video: false,
    vote_average: 7.356,
    vote_count: 435
  },
  {
    adult: false,
    backdrop_path: '/yOm993lsJyPmBodlYjgpPwBjXP9.jpg',
    genre_ids: [ 35, 10751, 14 ],
    id: 787699,
    original_language: 'en',
    original_title: 'Wonka',
    overview: 'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.',
    popularity: 1032.246,
    poster_path: '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
    release_date: '2023-12-06',
    title: 'Wonka',
    video: false,
    vote_average: 7.154,
    vote_count: 664
  },
  {
    adult: false,
    backdrop_path: '/ktHEdqmMWC1wdfPRMRCTZe2OISL.jpg',
    genre_ids: [ 27, 53, 9648 ],
    id: 1071215,
    original_language: 'en',
    original_title: 'Thanksgiving',
    overview: 'After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the holiday. Picking off residents one by one, what begins as random revenge killings are soon revealed to be part of a larger, sinister holiday plan.',
    popularity: 813.56,
    poster_path: '/f5f3TEVst1nHHyqgn7Z3tlwnBIH.jpg',
    release_date: '2023-11-16',
    title: 'Thanksgiving',
    video: false,
    vote_average: 6.698,
    vote_count: 329
  },
  {
    adult: false,
    backdrop_path: '/1jITxVJhkiFJuQuj8NcPLmDNtJg.jpg',
    genre_ids: [ 18, 35, 53 ],
    id: 930564,
    original_language: 'en',
    original_title: 'Saltburn',
    overview: "Struggling to find his place at Oxford University, student Oliver Quick finds himself drawn into the world of the charming and aristocratic Felix Catton, who invites him to Saltburn, his eccentric family's sprawling estate, for a summer never to be forgotten.",
    popularity: 795.299,
    poster_path: '/qjhahNLSZ705B5JP92YMEYPocPz.jpg',
    release_date: '2023-11-16',
    title: 'Saltburn',
    video: false,
    vote_average: 7.151,
    vote_count: 392
  },
  {
    adult: false,
    backdrop_path: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    genre_ids: [ 18, 36 ],
    id: 872585,
    original_language: 'en',
    original_title: 'Oppenheimer',
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 696.577,
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    release_date: '2023-07-19',
    title: 'Oppenheimer',
    video: false,
    vote_average: 8.119,
    vote_count: 5692
  },
  {
    adult: false,
    backdrop_path: '/vruRG9oFSC2QI3F6vLAsj1ND14S.jpg',
    genre_ids: [ 878, 28, 53, 27 ],
    id: 934194,
    original_language: 'en',
    original_title: 'Slash/Back',
    overview: 'In a remote Arctic community, a group of Inuit girls fight off an alien invasion, all while trying to make it to the coolest party in town.',
    popularity: 635.388,
    poster_path: '/fmmRFQtsRrNOpmcfoxVIyE1LxxT.jpg',
    release_date: '2022-06-24',
    title: 'Slash/Back',
    video: false,
    vote_average: 6.722,
    vote_count: 36
  },
  {
    adult: false,
    backdrop_path: '/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg',
    genre_ids: [ 28, 35 ],
    id: 897087,
    original_language: 'en',
    original_title: 'Freelance',
    overview: 'An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.',
    popularity: 630.456,
    poster_path: '/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg',
    release_date: '2023-10-05',
    title: 'Freelance',
    video: false,
    vote_average: 6.508,
    vote_count: 386
  },
  {
    adult: false,
    backdrop_path: '/1X7vow16X7CnCoexXh4H4F2yDJv.jpg',
    genre_ids: [ 80, 18, 36 ],
    id: 466420,
    original_language: 'en',
    original_title: 'Killers of the Flower Moon',
    overview: 'When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.',
    popularity: 627.914,
    poster_path: '/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg',
    release_date: '2023-10-18',
    title: 'Killers of the Flower Moon',
    video: false,
    vote_average: 7.549,
    vote_count: 1633
  },
  {
    adult: false,
    backdrop_path: '/jBOyi3ibJbVa1imTCcddPUxTVAV.jpg',
    genre_ids: [ 35, 27, 14 ],
    id: 956920,
    original_language: 'no',
    original_title: "There's Something in the Barn",
    overview: "An American family fulfills their dream of moving back to their roots after inheriting a remote cabin in the mountains of Norway. But there's a surprise waiting for them.",
    popularity: 610.581,
    poster_path: '/axrzMJR5VPWYNiW9ArENiMEPTjr.jpg',
    release_date: '2023-11-02',
    title: "There's Something in the Barn",
    video: false,
    vote_average: 6.784,
    vote_count: 67
  },
  {
    adult: false,
    backdrop_path: '/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg',
    genre_ids: [ 28, 12, 878 ],
    id: 670292,
    original_language: 'en',
    original_title: 'The Creator',
    overview: 'Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.',
    popularity: 591.312,
    poster_path: '/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg',
    release_date: '2023-09-27',
    title: 'The Creator',
    video: false,
    vote_average: 7.15,
    vote_count: 1628
  },
  {
    adult: false,
    backdrop_path: '/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg',
    genre_ids: [ 28, 80, 53 ],
    id: 385687,
    original_language: 'en',
    original_title: 'Fast X',
    overview: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 589.49,
    poster_path: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
    release_date: '2023-05-17',
    title: 'Fast X',
    video: false,
    vote_average: 7.191,
    vote_count: 4556
  },
  {
    adult: false,
    backdrop_path: '/9jPoyxjiEYPylUIMI3Ntixf8z3M.jpg',
    genre_ids: [ 16, 12, 35, 10751 ],
    id: 520758,
    original_language: 'en',
    original_title: 'Chicken Run: Dawn of the Nugget',
    overview: "A band of fearless chickens flock together to save poultry-kind from an unsettling new threat: a nearby farm that's cooking up something suspicious.",
    popularity: 578.679,
    poster_path: '/exNtEY8QUuQh9e23wSQjkPxKIU3.jpg',
    release_date: '2023-12-08',
    title: 'Chicken Run: Dawn of the Nugget',
    video: false,
    vote_average: 7.415,
    vote_count: 316
  },
  {
    adult: false,
    backdrop_path: '/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg',
    genre_ids: [ 16, 10751, 10402, 14, 35 ],
    id: 901362,
    original_language: 'en',
    original_title: 'Trolls Band Together',
    overview: "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
    popularity: 567.724,
    poster_path: '/bkpPTZUdq31UGDovmszsg2CchiI.jpg',
    release_date: '2023-10-12',
    title: 'Trolls Band Together',
    video: false,
    vote_average: 7.164,
    vote_count: 429
  },
  {
    adult: false,
    backdrop_path: '/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg',
    genre_ids: [ 27, 9648 ],
    id: 507089,
    original_language: 'en',
    original_title: "Five Nights at Freddy's",
    overview: "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
    popularity: 544.177,
    poster_path: '/7BpNtNfxuocYEVREzVMO75hso1l.jpg',
    release_date: '2023-10-25',
    title: "Five Nights at Freddy's",
    video: false,
    vote_average: 7.797,
    vote_count: 2980
  },
  {
    adult: false,
    backdrop_path: '/1pFSJ9lxMYLkgLS5gmnwm1AEiqx.jpg',
    genre_ids: [ 878 ],
    id: 798141,
    original_language: 'en',
    original_title: 'Doors',
    overview: 'Without warning, millions of mysterious alien “doors” suddenly appear around the globe. In a rush to determine the reason for their arrival, mankind must work together to understand the purpose of these cosmic anomalies.',
    popularity: 527.671,
    poster_path: '/pGPUXyhQTOqskKdDOD3Fmicqfc0.jpg',
    release_date: '2021-03-23',
    title: 'Doors',
    video: false,
    vote_average: 4.962,
    vote_count: 119
  },
  {
    adult: false,
    backdrop_path: '/gvNmnvu13TPAewP54hvCyuHwNwR.jpg',
    genre_ids: [ 28, 27, 878 ],
    id: 920081,
    original_language: 'en',
    original_title: 'Megaboa',
    overview: 'On a trip to Colombia, a group of college students encounter a fifty-foot boa constrictor, hungry for blood.',
    popularity: 526.376,
    poster_path: '/sAnAMv3eyQiGI1z2k8NsvH0Y6r5.jpg',
    release_date: '2021-11-26',
    title: 'Megaboa',
    video: false,
    vote_average: 6.5,
    vote_count: 442
  },
  {
    adult: false,
    backdrop_path: '/9PqD3wSIjntyJDBzMNuxuKHwpUD.jpg',
    genre_ids: [ 16, 35, 10751 ],
    id: 1075794,
    original_language: 'en',
    original_title: 'Leo',
    overview: 'Jaded 74-year-old lizard Leo has been stuck in the same Florida classroom for decades with his terrarium-mate turtle. When he learns he only has one year left to live, he plans to escape to experience life on the outside but instead gets caught up in the problems of his anxious students — including an impossibly mean substitute teacher.',
    popularity: 496.56,
    poster_path: '/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg',
    release_date: '2023-11-17',
    title: 'Leo',
    video: false,
    vote_average: 7.591,
    vote_count: 689
  },
  {
    adult: false,
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    genre_ids: [ 35, 12, 14 ],
    id: 346698,
    original_language: 'en',
    original_title: 'Barbie',
    overview: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    popularity: 484.672,
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    release_date: '2023-07-19',
    title: 'Barbie',
    video: false,
    vote_average: 7.163,
    vote_count: 6556
  },
  {
    adult: false,
    backdrop_path: '/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg',
    genre_ids: [ 28, 12, 53 ],
    id: 299054,
    original_language: 'en',
    original_title: 'Expend4bles',
    overview: 'Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.',   
    popularity: 432.639,
    poster_path: '/iwsMu0ehRPbtaSxqiaUDQB9qMWT.jpg',
    release_date: '2023-09-15',
    title: 'Expend4bles',
    video: false,
    vote_average: 6.433,
    vote_count: 941
  },
  {
    adult: false,
    backdrop_path: '/tLsc8SCFO0rMVgVyNm9XtfnyX84.jpg',
    genre_ids: [ 18, 9648, 53, 878 ],
    id: 726209,
    original_language: 'en',
    original_title: 'Leave the World Behind',
    overview: "A family's getaway to a luxurious rental home takes an ominous turn when a cyberattack knocks out their devices—and two strangers appear at their door.",
    popularity: 444.742,
    poster_path: '/5o0zzKBRHE9to6g9tYweP54WJa2.jpg',
    release_date: '2023-11-22',
    title: 'Leave the World Behind',
    video: false,
    vote_average: 6.532,
    vote_count: 1249
  },
  {
    adult: false,
    backdrop_path: '/5lWIYxYEqWi8j3ZloxXntw3ImBo.jpg',
    genre_ids: [ 16, 10751, 35, 14 ],
    id: 360920,
    original_language: 'en',
    original_title: 'The Grinch',
    overview: 'The Grinch hatches a scheme to ruin Christmas when the residents of Whoville plan their annual holiday celebration.',
    popularity: 358.235,
    poster_path: '/1Bc9VNd9CIHIyJtPKFqSQzrXWru.jpg',
    release_date: '2018-11-08',
    title: 'The Grinch',
    video: false,
    vote_average: 6.849,
    vote_count: 3614
  },
  {
    adult: false,
    backdrop_path: '/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg',
    genre_ids: [ 28, 12, 878 ],
    id: 667538,
    original_language: 'en',
    original_title: 'Transformers: Rise of the Beasts',
    overview: 'When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.',
    popularity: 389.682,
    poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
    release_date: '2023-06-06',
    title: 'Transformers: Rise of the Beasts',
    video: false,
    vote_average: 7.41,
    vote_count: 3780
  },
  {
    adult: false,
    backdrop_path: '/ptz5ETMxDoRRiE69BVuIxJzyTEO.jpg',
    genre_ids: [ 16, 35, 12, 10751, 28 ],
    id: 940551,
    original_language: 'en',
    original_title: 'Migration',
    overview: 'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.',
    popularity: 418.65,
    poster_path: '/ldfCF9RhR40mppkzmftxapaHeTo.jpg',
    release_date: '2023-12-06',
    title: 'Migration',
    video: false,
    vote_average: 7.3,
    vote_count: 61
  },
  {
    adult: false,
    backdrop_path: '/bg66dvmJg3ReDzfppT748SIJRmw.jpg',
    genre_ids: [ 27 ],
    id: 1131755,
    original_language: 'en',
    original_title: 'A Creature Was Stirring',
    overview: "A nurse taking care of her daughter's mysterious affliction struggles to hide her secrets when uninvited strangers take shelter in her house during a lethal blizzard.",
    popularity: 317.134,
    poster_path: '/ikQG3byEFyfwcnF0zmyNtXTmr5v.jpg',
    release_date: '2023-12-08',
    title: 'A Creature Was Stirring',
    video: false,
    vote_average: 4.4,
    vote_count: 8
  },
  {
    adult: false,
    backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
    genre_ids: [ 16, 10751, 12, 14, 35 ],
    id: 502356,
    original_language: 'en',
    original_title: 'The Super Mario Bros. Movie',
    overview: 'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
    popularity: 416.511,
    poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
    release_date: '2023-04-05',
    title: 'The Super Mario Bros. Movie',
    video: false,
    vote_average: 7.718,
    vote_count: 7578
  },
  {
    adult: false,
    backdrop_path: '/628Dep6AxEtDxjZoGP78TsOxYbK.jpg',
    genre_ids: [ 28, 53 ],
    id: 575264,
    original_language: 'en',
    original_title: 'Mission: Impossible - Dead Reckoning Part One',
    overview: "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
    popularity: 380.057,
    poster_path: '/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
    release_date: '2023-07-08',
    title: 'Mission: Impossible - Dead Reckoning Part One',
    video: false,
    vote_average: 7.584,
    vote_count: 2769
  },
  {
    adult: false,
    backdrop_path: '/sy0vo1cmpKqwPRiMUiJ45jyLsX7.jpg',
    genre_ids: [ 10751, 35, 14 ],
    id: 8871,
    original_language: 'en',
    original_title: 'How the Grinch Stole Christmas',
    overview: 'The Grinch decides to rob Whoville of Christmas - but a dash of kindness from little Cindy Lou Who and her family may be enough to melt his heart...',
    popularity: 329.928,
    poster_path: '/AmUs3hximCKa90sHuIRr5Bz8ci5.jpg',
    release_date: '2000-11-17',
    title: 'How the Grinch Stole Christmas',
    video: false,
    vote_average: 6.768,
    vote_count: 6993
  },
  {
    adult: false,
    backdrop_path: '/4mmrgZW9bcgMRFdV1lCcXqCEXEr.jpg',
    genre_ids: [ 28, 18, 12, 9648, 53 ],
    id: 755401,
    original_language: 'en',
    original_title: 'Skydog',
    overview: 'After a high school senior working on his pilot’s license rescues a dog named Oreo, he finds out his mom is a CIA agent who’s been captured. He teams up with Oreo and a new friend to find his mother and uncover double agents inside the CIA.',
    popularity: 520.16,
    poster_path: '/5M3bY1rl9QIQSmrAGPEt9qutj64.jpg',
    release_date: '2020-10-20',
    title: 'Skydog',
    video: false,
    vote_average: 7.2,
    vote_count: 8
  },
  {
    adult: false,
    backdrop_path: '/4MUfDtBqUFqotGF5RJOfNfoBTLo.jpg',
    genre_ids: [ 28, 27, 14 ],
    id: 951546,
    original_language: 'en',
    original_title: 'Reign of Chaos',
    overview: "When the world is gripped by a plague unleashed by the evil lord Chaos, and humans are turned into rabid creatures, mankind can only be saved by three young women, descendants of a Goddess, with the power to stop Chaos' evil.",
    popularity: 336.07,
    poster_path: '/nTMmpvR9TyV631tpFr4FtYxG0FC.jpg',
    release_date: '2022-04-12',
    title: 'Reign of Chaos',
    video: false,
    vote_average: 5.983,
    vote_count: 30
  },
  {
    adult: false,
    backdrop_path: '/ehumsuIBbgAe1hg343oszCLrAfI.jpg',
    genre_ids: [ 16, 10751, 14, 12 ],
    id: 1022796,
    original_language: 'en',
    original_title: 'Wish',
    overview: 'Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.',
    popularity: 342.376,
    poster_path: '/8QtDhh8mnGUEyrJsaeb3kYgDRaA.jpg',
    release_date: '2023-11-13',
    title: 'Wish',
    video: false,
    vote_average: 6.538,
    vote_count: 186
  },
  {
    adult: false,
    backdrop_path: '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
    genre_ids: [ 28, 12, 878 ],
    id: 634649,
    original_language: 'en',
    original_title: 'Spider-Man: No Way Home',
    overview: 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
    popularity: 323.409,
    poster_path: '/5weKu49pzJCt06OPpjvT80efnQj.jpg',
    release_date: '2021-12-15',
    title: 'Spider-Man: No Way Home',
    video: false,
    vote_average: 7.982,
    vote_count: 18727
  },
  {
    adult: false,
    backdrop_path: '/5mzr6JZbrqnqD8rCEvPhuCE5Fw2.jpg',
    genre_ids: [ 28, 878, 27 ],
    id: 615656,
    original_language: 'en',
    original_title: 'Meg 2: The Trench',
    overview: 'An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.',
    popularity: 357.774,
    poster_path: '/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg',
    release_date: '2023-08-02',
    title: 'Meg 2: The Trench',
    video: false,
    vote_average: 6.7,
    vote_count: 2733
  },
  {
    adult: false,
    backdrop_path: '/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg',
    genre_ids: [ 878, 27, 28 ],
    id: 940721,
    original_language: 'ja',
    original_title: 'ゴジラ-1.0',
    overview: 'In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?',
    popularity: 415.158,
    poster_path: '/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg',
    release_date: '2023-11-03',
    title: 'Godzilla Minus One',
    video: false,
    vote_average: 8.055,
    vote_count: 199
  },
  {
    adult: false,
    backdrop_path: '/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg',
    genre_ids: [ 16, 35, 10751, 14, 10749 ],
    id: 976573,
    original_language: 'en',
    original_title: 'Elemental',
    overview: 'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
    popularity: 392.835,
    poster_path: '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg',
    release_date: '2023-06-14',
    title: 'Elemental',
    video: false,
    vote_average: 7.71,
    vote_count: 3307
  },
  {
    adult: false,
    backdrop_path: '/ufR7C4AtkqS0INda0qBICpupOxy.jpg',
    genre_ids: [ 28, 53, 18 ],
    id: 982932,
    original_language: 'en',
    original_title: 'Shrapnel',
    overview: 'A former Marine and his old war buddy face off against the Mexican cartel behind the disappearance of his daughter.',
    popularity: 257.367,
    poster_path: '/gsRDrAML7hJC8ZCgRQobHIrzbxR.jpg',
    release_date: '2023-07-28',
    title: 'Shrapnel',
    video: false,
    vote_average: 6,
    vote_count: 19
  },
  {
    adult: false,
    backdrop_path: '/8rpDcsfLJypbO6vREc0547VKqEv.jpg',
    genre_ids: [ 878, 12, 28 ],
    id: 76600,
    original_language: 'en',
    original_title: 'Avatar: The Way of Water',
    overview: 'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    popularity: 345.695,
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    release_date: '2022-12-14',
    title: 'Avatar: The Way of Water',
    video: false,
    vote_average: 7.648,
    vote_count: 10455
  },
  {
    adult: false,
    backdrop_path: '/9QusGjxcYvfPD1THg6oW3RLeNn7.jpg',
    genre_ids: [ 28, 12, 14 ],
    id: 297802,
    original_language: 'en',
    original_title: 'Aquaman',
    overview: "Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm's half-human, half-Atlantean brother and true heir to the throne.",
    popularity: 311.357,
    poster_path: '/xLPffWMhMj1l50ND3KchMjYoKmE.jpg',
    release_date: '2018-12-07',
    title: 'Aquaman',
    video: false,
    vote_average: 6.9,
    vote_count: 13212
  },
  {
    adult: false,
    backdrop_path: '/X8yF6STUk5Zr5nAuLBJiio8Sxh.jpg',
    genre_ids: [ 18, 10749 ],
    id: 1143183,
    original_language: 'tl',
    original_title: 'Rewind',
    overview: "Mary (Marian Rivera) loves John (Dingdong Dantes) for as long as she can remember. But after years of marriage, John's priorities shift, leading to a strained relationship with Mary, which causes a tragic accident that takes away Mary's life. Until one day, John gets an extraordinary proposition - to rewind time and save the life of the woman he loves.",
    popularity: 493.072,
    poster_path: '/vW80VheMJhHsj0pDVYJL3qAMWMd.jpg',
    release_date: '2023-12-25',
    title: 'Rewind',
    video: false,
    vote_average: 0,
    vote_count: 0
  },
  {
    adult: false,
    backdrop_path: '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    genre_ids: [ 16, 28, 12, 878 ],
    id: 569094,
    original_language: 'en',
    original_title: 'Spider-Man: Across the Spider-Verse',
    overview: 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',   
    popularity: 354.512,
    poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    release_date: '2023-05-31',
    title: 'Spider-Man: Across the Spider-Verse',
    video: false,
    vote_average: 8.388,
    vote_count: 5320
  },
  {
    adult: false,
    backdrop_path: '/dyA6hSkM0rOIOjIAXHPXTiQ0wxO.jpg',
    genre_ids: [ 28, 35, 80 ],
    id: 1189927,
    original_language: 'es',
    original_title: 'El duelo',
    overview: '',
    popularity: 351.006,
    poster_path: '/nFjcIyURaXrU4WWRN7obbipFQGy.jpg',
    release_date: '2023-10-12',
    title: 'El duelo',
    video: false,
    vote_average: 8.5,
    vote_count: 0
  },
  {
    adult: false,
    backdrop_path: '/jhpsTzbXEu5bkCPmBqxv7vUTjIT.jpg',
    genre_ids: [ 14, 12, 878, 28 ],
    id: 566810,
    original_language: 'en',
    original_title: 'Dragon Kingdom',
    overview: 'To save their Kingdom from an army of undead, a group of warriors must travel through the forbidden lands fighting the fearsome beasts that call The Dark Kingdom their home.',
    popularity: 316.737,
    poster_path: '/o7StI2iR8yY1N67meSkNcXfojyD.jpg',
    release_date: '2018-11-26',
    title: 'The Dark Kingdom',
    video: false,
    vote_average: 5.6,
    vote_count: 43
  },
  {
    adult: false,
    backdrop_path: '/tC78Pck2YCsUAtEdZwuHYUFYtOj.jpg',
    genre_ids: [ 28, 53, 80 ],
    id: 926393,
    original_language: 'en',
    original_title: 'The Equalizer 3',
    overview: "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
    popularity: 324.466,
    poster_path: '/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg',
    release_date: '2023-08-30',
    title: 'The Equalizer 3',
    video: false,
    vote_average: 7.421,
    vote_count: 1976
  },
  {
    adult: false,
    backdrop_path: '/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg',
    genre_ids: [ 28, 18 ],
    id: 678512,
    original_language: 'en',
    original_title: 'Sound of Freedom',
    overview: 'The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.',
    popularity: 288.54,
    poster_path: '/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg',
    release_date: '2023-07-03',
    title: 'Sound of Freedom',
    video: false,
    vote_average: 8.074,
    vote_count: 1669
  },
  {
    adult: false,
    backdrop_path: '/pwvVS1AiRWLropqJ03i5ovynZhk.jpg',
    genre_ids: [ 27, 53 ],
    id: 517929,
    original_language: 'en',
    original_title: 'Fog City',
    overview: 'A group of friends seal themselves inside a secluded Cape Cod vacation home after a mysterious orange fog leaks from an old nearby factory. Once trapped, they quickly learn there is no escape.',       
    popularity: 278.934,
    poster_path: '/isewxmxthIUrmPpGHQQlIuOid3s.jpg',
    release_date: '2023-10-20',
    title: 'Fog City',
    video: false,
    vote_average: 3,
    vote_count: 2
  },
  {
    adult: false,
    backdrop_path: '/AucuqDaUW4z1oT5XyL71qwRY2F6.jpg',
    genre_ids: [ 27, 53 ],
    id: 983507,
    original_language: 'no',
    original_title: 'Meg, deg & Frank',
    overview: "Christian - a millionaire heir, meets Sigrid - a young student, on a dating app. They hit it off quickly, but there's only one problem: Christian lives with Frank, a man who dresses up and constantly acts like a dog.",
    popularity: 263.024,
    poster_path: '/9DPG1gxLwV2oyFdHq3SnISsWbse.jpg',
    release_date: '2022-06-03',
    title: 'Good Boy',
    video: false,
    vote_average: 6.637,
    vote_count: 117
  },
  {
    adult: false,
    backdrop_path: '/kBBMF7GWYXzdRSk5w4xwip7yk3U.jpg',
    genre_ids: [ 28, 53, 80 ],
    id: 603692,
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview: 'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    popularity: 342.984,
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    release_date: '2023-03-22',
    title: 'John Wick: Chapter 4',
    video: false,
    vote_average: 7.773,
    vote_count: 5245
  },
  {
    adult: false,
    backdrop_path: '/sERD1155J1cJyXug1QwlA0fa354.jpg',
    genre_ids: [ 14 ],
    id: 995906,
    original_language: 'en',
    original_title: 'Galaxy Games',
    overview: 'A group of young adults are sent to a faraway planet to compete in the prestigious Sol Invictus games. When disaster strikes and the teams are stranded without equipment or communication, they must work together to survive long enough to be rescued.',
    popularity: 240.18,
    poster_path: '/8aoIMYZUu8DRrJFkDvz13rehSFL.jpg',
    release_date: '2022-07-04',
    title: 'Galaxy Games',
    video: false,
    vote_average: 5.714,
    vote_count: 7
  },
  {
    adult: false,
    backdrop_path: '/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg',
    genre_ids: [ 878, 12, 28 ],
    id: 609681,
    original_language: 'en',
    original_title: 'The Marvels',
    overview: 'Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.',
    popularity: 311.3,
    poster_path: '/Ag3D9qXjhJ2FUkrlJ0Cv1pgxqYQ.jpg',
    release_date: '2023-11-08',
    title: 'The Marvels',
    video: false,
    vote_average: 6.45,
    vote_count: 747
  },
  {
    adult: false,
    backdrop_path: '/mIpdOcss3oedSYB8juiSXg89uLL.jpg',
    genre_ids: [ 28, 878, 12, 53 ],
    id: 479753,
    original_language: 'en',
    original_title: 'Shockwave: Countdown to Disaster',
    overview: 'A stolen seismic weapon is activated in Yemen. A hostage freed there tries in vain to warn against its global effect. It starts seismic activity at the Californian fault line where her daughter and ex are monitoring it. Can they stop it?',
    popularity: 247.507,
    poster_path: '/sBD608VF4TcFHmP7SuC0OcvZQ0b.jpg',
    release_date: '2017-09-02',
    title: 'Shockwave: Countdown to Disaster',
    video: false,
    vote_average: 5.711,
    vote_count: 57
  },
  {
    adult: false,
    backdrop_path: '/tB59fpPnQITgnfxPfMf2gxASTeC.jpg',
    genre_ids: [ 28, 53, 18 ],
    id: 656156,
    original_language: 'ko',
    original_title: '보호자',
    overview: "After 10 years of incarceration on behalf of his employer, all Su-hyuk wants is a normal life - one he hopes will include his former girlfriend, Min-seo, and their daughter, In-bi. But once you've penetrated the upper echelons of the underworld, normal can prove hard to come by. Sometime in the past decade, meanwhile, Su-hyuk's employer has adopted an air of legitimacy. These days, the old gang steal and murder in the name of urban development. And they want the reluctant Su-hyuk on board.",
    popularity: 273.586,
    poster_path: '/ePwZs1oOh4pg8UZP8DuVZZeIn89.jpg',
    release_date: '2023-08-15',
    title: 'A Man of Reason',
    video: false,
    vote_average: 6.5,
    vote_count: 33
  },
  {
    adult: false,
    backdrop_path: '/faXT8V80JRhnArTAeYXz0Eutpv9.jpg',
    genre_ids: [ 12, 14, 16, 35, 10751, 28 ],
    id: 315162,
    original_language: 'en',
    original_title: 'Puss in Boots: The Last Wish',
    overview: 'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
    popularity: 270.166,
    poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
    release_date: '2022-12-07',
    title: 'Puss in Boots: The Last Wish',
    video: false,
    vote_average: 8.26,
    vote_count: 6777
  },
  {
    adult: false,
    backdrop_path: '/lDlVgD9IGAmki7CgIlH5eYUwrhW.jpg',
    genre_ids: [ 28, 12, 878 ],
    id: 857879,
    original_language: 'en',
    original_title: 'Mount Adams',
    overview: 'UFO investigators find themselves fighting for survival as alien monsters hunt them on the slopes of Mount Adams.',
    popularity: 251.872,
    poster_path: '/nddTKKAu6z771duaxr1D32pHZ8j.jpg',
    release_date: '2021-07-21',
    title: 'Mount Adams',
    video: false,
    vote_average: 6.5,
    vote_count: 9
  },
  {
    adult: false,
    backdrop_path: '/h3X1YZXNeklLNKRVOS6DHGRosog.jpg',
    genre_ids: [ 27, 35, 14 ],
    id: 287903,
    original_language: 'en',
    original_title: 'Krampus',
    overview: 'When his dysfunctional family clashes over the holidays, young Max is disillusioned and turns his back on Christmas.  Little does he know, this lack of festive spirit has unleashed the wrath of Krampus: a demonic force of ancient evil intent on punishing non-believers.',
    popularity: 229.669,
    poster_path: '/sAolMRD9rFSTU7tssfFuLEJJa7w.jpg',
    release_date: '2015-11-26',
    title: 'Krampus',
    video: false,
    vote_average: 6.197,
    vote_count: 2033
  },
  {
    adult: false,
    backdrop_path: '/uSUjIzqKyebAd2wqDyb11Ya4wch.jpg',
    genre_ids: [ 28, 10752 ],
    id: 1062482,
    original_language: 'en',
    original_title: "Condor's Nest",
    overview: "American war veteran Will Spalding has tracked the sadistic Nazi Colonel who executed his bomber crew during WWII to a remote location in South America. But he is in for more than he bargained for when he uncovers a secret Nazi headquarters known as the Condor's Nest.",
    popularity: 399.389,
    poster_path: '/aBAsCMzsbGlFtQFqeWsKWM6hvOE.jpg',
    release_date: '2023-01-27',
    title: "Condor's Nest",
    video: false,
    vote_average: 5.4,
    vote_count: 12
  },
  {
    adult: false,
    backdrop_path: '/s8ryrjpl6GjSLoEHagzmgE4Yl2f.jpg',
    genre_ids: [ 27, 53 ],
    id: 844069,
    original_language: 'ko',
    original_title: '귀문',
    overview: "In 1990, at a secluded community center, the custodian murders all the guest lodgers and kills himself. Ever since, on every Old Year's Night, paranormal events begin to take place within the building. Eventually, the center is shut down and left abandoned for years. A renowned paranormal investigator who had lost his mother during an exorcism and three college students who heard about the rumor of the unexplained phenomena heads over to the building, resolved to uncover the buried secret.",
    popularity: 226.216,
    poster_path: '/e1cZ4LaYv1M1RThyUh1sVi21Loe.jpg',
    release_date: '2021-08-25',
    title: 'Guimoon: The Lightless Door',
    video: false,
    vote_average: 6.706,
    vote_count: 80
  },
  {
    adult: false,
    backdrop_path: '/xFYpUmB01nswPgbzi8EOCT1ZYFu.jpg',
    genre_ids: [ 12, 28, 18 ],
    id: 980489,
    original_language: 'en',
    original_title: 'Gran Turismo',
    overview: 'The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.',
    popularity: 266.131,
    poster_path: '/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg',
    release_date: '2023-08-09',
    title: 'Gran Turismo',
    video: false,
    vote_average: 7.992,
    vote_count: 1683
  },
  {
  adult: false,
  backdrop_path: '/evxXVJtomJJbAXcDxF6wsCJzVDe.jpg',
  genre_ids: [ 27 ],
  id: 1019836,
  original_language: 'en',
  original_title: 'Christmas Bloody Christmas',
  overview: "It's Christmas Eve and Tori just wants to get drunk and party, but when a robotic Santa Claus at a nearby toy store goes haywire and begins a rampant killing spree through her small town, she's forced into a battle for survival.",
  popularity: 237.764,
  poster_path: '/97PaQ7r4H3y0x9RTXusfedmzf86.jpg',
  release_date: '2022-10-05',
  title: 'Christmas Bloody Christmas',
  video: false,
  vote_average: 5.565,
  vote_count: 169
},
{
  adult: false,
  backdrop_path: '/3d39m2S3WynknLVGpsOxhiSKbgQ.jpg',
  genre_ids: [ 53, 28 ],
  id: 1146225,
  original_language: 'en',
  original_title: 'Escaping Paradise',
  overview: 'When a young couple vacations on an exotic island, they encounter a dangerous fugitive who is determined to keep them from leaving.',
  popularity: 210.199,
  poster_path: '/3UCTls0hVKMCwWtkTmwKcCOzlgu.jpg',
  release_date: '2023-07-08',
  title: 'Escaping Paradise',
  video: false,
  vote_average: 4.7,
  vote_count: 3
},
{
  adult: false,
  backdrop_path: '/gN79aDbZdaSJkFS1iVA17HplF2X.jpg',
  genre_ids: [ 27, 9648, 53 ],
  id: 968051,
  original_language: 'en',
  original_title: 'The Nun II',
  overview: 'In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.',
  popularity: 234.985,
  poster_path: '/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg',
  release_date: '2023-09-06',
  title: 'The Nun II',
  video: false,
  vote_average: 6.882,
  vote_count: 1562
},
{
  adult: false,
  backdrop_path: '/hRPKfuotMeyRiXXGPKmmrVXD5DG.jpg',
  genre_ids: [ 28 ],
  id: 504148,
  original_language: 'en',
  original_title: 'The Serpent',
  overview: "Top special agent Lucinda Kavsky works for a secret part of the CIA. She's given a special assignment but then set up by her own agency.",
  popularity: 378.83,
  poster_path: '/AvMoan3rxCDZpNf59BmAP2G8q5x.jpg',
  release_date: '2021-01-28',
  title: 'The Serpent',
  video: false,
  vote_average: 3.8,
  vote_count: 12
},
{
  adult: false,
  backdrop_path: '/lntyt4OVDbcxA1l7LtwITbrD3FI.jpg',
  genre_ids: [ 18, 10749 ],
  id: 1010581,
  original_language: 'es',
  original_title: 'Culpa mía',
  overview: "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
  popularity: 264.849,
  poster_path: '/w46Vw536HwNnEzOa7J24YH9DPRS.jpg',
  release_date: '2023-06-08',
  title: 'My Fault',
  video: false,
  vote_average: 8.066,
  vote_count: 2060
},
{
  adult: false,
  backdrop_path: '/ixZzr4PyM2TPs5fka3IJj058WYo.jpg',
  genre_ids: [ 28, 878, 12 ],
  id: 565770,
  original_language: 'en',
  original_title: 'Blue Beetle',
  overview: 'Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.',   
  popularity: 282.459,
  poster_path: '/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg',
  release_date: '2023-08-16',
  title: 'Blue Beetle',
  video: false,
  vote_average: 6.896,
  vote_count: 1941
},
{
  adult: false,
  backdrop_path: '/rb3QQ2TQfJoCpCZlfXBlBbzYy1D.jpg',
  genre_ids: [ 53, 28 ],
  id: 844416,
  original_language: 'en',
  original_title: 'Rumble Through the Dark',
  overview: 'Set in the dark landscape of the Mississippi Delta, where a former bare-knuckle fighter must win one last fight to pay off his debts to the local mob boss and save his childhood home—the stakes nothing less than life or death.',
  popularity: 232.66,
  poster_path: '/19UbYIT9WEQS5qSD3BREDxVXk8g.jpg',
  release_date: '2023-11-03',
  title: 'Rumble Through the Dark',
  video: false,
  vote_average: 6.625,
  vote_count: 28
},
{
  adult: false,
  backdrop_path: '/1bI74dmPkYrbb2GFMBjxkqKXDVi.jpg',
  genre_ids: [ 27 ],
  id: 1033667,
  original_language: 'zh',
  original_title: '粽邪3：鬼門開',
  overview: 'Aspiring to become a parkour influencer, a gifted young man from an exorcist family gets caught up in a swirl of spooky events at an eerie hotel.',
  popularity: 204.855,
  poster_path: '/ocb5sGHk00Kw30qxdNJGfqvKWnl.jpg',
  release_date: '2023-08-25',
  title: 'The Rope Curse 3',
  video: false,
  vote_average: 4.778,
  vote_count: 9
},
{
  adult: false,
  backdrop_path: '/yF1eOkaYvwiORauRCPWznV9xVvi.jpg',
  genre_ids: [ 28, 12, 878 ],
  id: 298618,
  original_language: 'en',
  original_title: 'The Flash',
  overview: "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
  popularity: 263.933,
  poster_path: '/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg',
  release_date: '2023-06-13',
  title: 'The Flash',
  video: false,
  vote_average: 6.805,
  vote_count: 3400
},
{
  adult: false,
  backdrop_path: '/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg',
  genre_ids: [ 27, 53 ],
  id: 951491,
  original_language: 'en',
  original_title: 'Saw X',
  overview: "Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.",
  popularity: 266.707,
  poster_path: '/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg',
  release_date: '2023-09-26',
  title: 'Saw X',
  video: false,
  vote_average: 7.39,
  vote_count: 1322
},
{
  adult: false,
  backdrop_path: '/zgQQF04u3OgNBJqClRNby1FPz9s.jpg',
  genre_ids: [
     16, 10751, 28,
    878,    35, 18,
     12
  ],
  id: 893723,
  original_language: 'en',
  original_title: 'PAW Patrol: The Mighty Movie',
  overview: 'A magical meteor crash lands in Adventure City and gives the PAW Patrol pups superpowers, transforming them into The Mighty Pups.',
  popularity: 241.069,
  poster_path: '/aTvePCU7exLepwg5hWySjwxojQK.jpg',
  release_date: '2023-09-21',
  title: 'PAW Patrol: The Mighty Movie',
  video: false,
  vote_average: 6.943,
  vote_count: 192
},
{
  adult: false,
  backdrop_path: '/pnkcE3Q3fPNM9XzWEN1gJJRYYX4.jpg',
  genre_ids: [ 35, 10751, 12 ],
  id: 772,
  original_language: 'en',
  original_title: 'Home Alone 2: Lost in New York',
  overview: "Instead of flying to Florida with his folks, Kevin ends up alone in New York, where he gets a hotel room with his dad's credit card—despite problems from a clerk and meddling bellboy. But when Kevin runs into his old nemeses, the Wet Bandits, he's determined to foil their plans to rob a toy store on Christmas Eve.",
  popularity: 219.522,
  poster_path: '/uuitWHpJwxD1wruFl2nZHIb4UGN.jpg',
  release_date: '1992-11-19',
  title: 'Home Alone 2: Lost in New York',
  video: false,
  vote_average: 6.725,
  vote_count: 8955
},
{
  adult: false,
  backdrop_path: '/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg',
  genre_ids: [ 28, 53, 80 ],
  id: 762430,
  original_language: 'en',
  original_title: 'Retribution',
  overview: 'When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks- all with his kids trapped in the back seat.',     
  popularity: 231.279,
  poster_path: '/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg',
  release_date: '2023-08-23',
  title: 'Retribution',
  video: false,
  vote_average: 6.901,
  vote_count: 776
},
{
  adult: false,
  backdrop_path: '/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg',
  genre_ids: [ 12, 28 ],
  id: 335977,
  original_language: 'en',
  original_title: 'Indiana Jones and the Dial of Destiny',
  overview: "Finding himself in a new era, and approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
  popularity: 256.536,
  poster_path: '/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg',
  release_date: '2023-06-28',
  title: 'Indiana Jones and the Dial of Destiny',
  video: false,
  vote_average: 6.662,
  vote_count: 2445
},
{
  adult: false,
  backdrop_path: '/biRLtgt3t8MwxeLRRJkf1BsHoeq.jpg',
  genre_ids: [ 28, 53 ],
  id: 1060090,
  original_language: 'en',
  original_title: 'The Collective',
  overview: 'A group of righteous assassins called The Collective take aim at a highly sophisticated human trafficking ring backed by a network of untouchable billionaires. With their backs against the wall, The Collective has no choice but to put their most important mission in the hands of rookie assassin, Sam Alexander.',
  popularity: 220.083,
  poster_path: '/Ah9H6Sj434nJiZpTPQrovHaEePV.jpg',
  release_date: '2023-08-04',
  title: 'The Collective',
  video: false,
  vote_average: 5.922,
  vote_count: 58
},
{
  adult: false,
  backdrop_path: '/fLZJM6ECTg3XgYuPHwpvRMqCgCl.jpg',
  genre_ids: [ 28, 12, 10751, 878 ],
  id: 549945,
  original_language: 'nl',
  original_title: 'De Club van Lelijke Kinderen',
  overview: '“Keep it clean!” – The new president is serious about that, including looks. When Paul, whose large jug ears are quite apparent on class photo day, and some of the other “ugly” kids are taken on a surprise trip, they realize that the president wants to hide them away. On the run, Paul is helped by Sara, one of the “pretty” kids. They start an underground club to fight against the president. The movement soon turns into a revolution. The kids show the world that even children can rise up – and that you don’t have to be “pretty” to be a hero!',
  popularity: 356.769,
  poster_path: '/wDEXvrSrfJxy1MJFeezrYb5fSv7.jpg',
  release_date: '2019-10-09',
  title: 'The Club of Ugly Children',
  video: false,
  vote_average: 6.6,
  vote_count: 22
},
{
  adult: false,
  backdrop_path: '/8g9ZdvHX6jszRY71aVtpRUmHQzJ.jpg',
  genre_ids: [ 18, 53 ],
  id: 958182,
  original_language: 'es',
  original_title: 'Heroico',
  overview: 'Luis, an 18-year-old boy with Indigenous roots, enters the Heroic Military College in hopes of ensuring a better future. There, he encounters a rigid and institutionally violent system designed to turn him into a perfect soldier.',
  popularity: 223.475,
  poster_path: '/tRD18JW9iKqmwkQKvzPYDQetRoI.jpg',
  release_date: '2023-09-21',
  title: 'Heroic',
  video: false,
  vote_average: 7.617,
  vote_count: 77
},
{
  adult: false,
  backdrop_path: '/awWppR6CmJ6gqM6UjMz5DJ4zZaP.jpg',
  genre_ids: [ 36, 28, 18 ],
  id: 960481,
  original_language: 'mn',
  original_title: 'Хотулун гүнж: Алтан судрын эрэлд',
  overview: 'Princess Khotulun is the daughter of Haidu Khan of the Ugudei dynasty. The film tells the story of Princess Khotulun, the son of Kublai Khan, known in Western and Eastern history as a wrestling princess, and her struggle to reclaim her Golden Sutra.',
  popularity: 213.567,
  poster_path: '/dhD4QNmZwfh88y4Dm5XsX7dWFVf.jpg',
  release_date: '2021-12-03',
  title: 'Princess Khutulun',
  video: false,
  vote_average: 7.147,
  vote_count: 51
},
{
  adult: false,
  backdrop_path: '/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg',
  genre_ids: [ 18, 36, 10752 ],
  id: 753342,
  original_language: 'en',
  original_title: 'Napoleon',
  overview: 'An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.',
  popularity: 231.755,
  poster_path: '/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg',
  release_date: '2023-11-22',
  title: 'Napoleon',
  video: false,
  vote_average: 6.372,
  vote_count: 842
},
{
  adult: false,
  backdrop_path: '/h4Co2COineKeJfM3Z3L0uJsQzSa.jpg',
  genre_ids: [ 28, 12, 35 ],
  id: 598413,
  original_language: 'en',
  original_title: 'Send It!',
  overview: "An extreme sportsman's life forever changes upon departing his simple Texas roots to compete in the world's most prestigious Kiteboarding Championship. Along the way, an edgy street-smart girl challenges him well beyond just kiting.",
  popularity: 176.681,
  poster_path: '/iSrsifEI49pfyewDJtGcQpFZ11W.jpg',
  release_date: '2021-05-11',
  title: 'Send It!',
  video: false,
  vote_average: 5.9,
  vote_count: 11
},
{
    adult: false,
    backdrop_path: '/46Os8U0DEPmI0OnvKDxucl6SLVZ.jpg',
    genre_ids: [ 27, 53 ],
    id: 1008042,
    original_language: 'en',
    original_title: 'Talk to Me',
    overview: 'When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.',     
    popularity: 245.418,
    poster_path: '/kdPMUMJzyYAc4roD52qavX0nLIC.jpg',
    release_date: '2023-07-26',
    title: 'Talk to Me',
    video: false,
    vote_average: 7.199,
    vote_count: 1950
  },
  {
    adult: false,
    backdrop_path: '/mZbGLiSscsF2ipFt7su7gmSLn8l.jpg',
    genre_ids: [ 16, 35, 10751 ],
    id: 13248,
    original_language: 'en',
    original_title: 'Bah, Humduck!: A Looney Tunes Christmas',
    overview: "In this adaptation of Charles Dickens' A Christmas Carol, Daffy Duck is the greedy proprietor of the Lucky Duck Mega-Mart and all he can think about is the money to be made during the holiday season.",
    popularity: 214.637,
    poster_path: '/f568JOtSlQoevRIDBKK3YIkHbvd.jpg',
    release_date: '2006-11-14',
    title: 'Bah, Humduck!: A Looney Tunes Christmas',
    video: false,
    vote_average: 7.246,
    vote_count: 116
  },
  {
    adult: false,
    backdrop_path: '/iaMIylLoN7Y3CvrA0pg2ZFKjk26.jpg',
    genre_ids: [ 10752, 18, 28 ],
    id: 1047925,
    original_language: 'en',
    original_title: 'Come Out Fighting',
    overview: 'In WWII, a squad of U.S. African-American soldiers are sent on a rescue mission behind enemy lines to locate their lost commanding officer and a downed fighter pilot.',
    popularity: 206.018,
    poster_path: '/sERwJxz0sqsbcUoTm66l9pI6HcH.jpg',
    release_date: '2023-05-19',
    title: 'Come Out Fighting',
    video: false,
    vote_average: 5.1,
    vote_count: 26
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 99 ],
    id: 645488,
    original_language: 'en',
    original_title: 'Aquaman: Heroines of Atlantis',
    overview: 'Amber Heard and Nicole Kidman discuss their characters Mera and Atlanna.',
    popularity: 227.659,
    poster_path: '/pa7m8nqDrEi7hAGB5vTnCkGLPC2.jpg',
    release_date: '2019-03-26',
    title: 'Aquaman: Heroines of Atlantis',
    video: false,
    vote_average: 6.108,
    vote_count: 37
  },
  {
    adult: false,
    backdrop_path: '/sxmazOtNWi6IiZ1QqG0wkliHzgA.jpg',
    genre_ids: [ 27, 53, 18 ],
    id: 762079,
    original_language: 'fr',
    original_title: 'Le Calendrier',
    overview: 'Eva, an ex-dancer, is now living in a wheelchair, unable to walk. When her friend Sophie gives her an old wooden antique advent calendar before Christmas, she realizes each window contains a surprise that triggers repercussions in real life: some of them good, but most of them bad... Now Eva will have to choose between getting rid of the calendar or walking again… even if it causes death around her.',
    popularity: 199.969,
    poster_path: '/psaYUHDotafhVNAE1pZN2GkRXJY.jpg',
    release_date: '2021-12-01',
    title: 'The Advent Calendar',
    video: false,
    vote_average: 6.629,
    vote_count: 244
  },
  {
    adult: false,
    backdrop_path: '/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
    genre_ids: [ 878, 12, 28 ],
    id: 447365,
    original_language: 'en',
    original_title: 'Guardians of the Galaxy Vol. 3',
    overview: 'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
    popularity: 241.512,
    poster_path: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
    release_date: '2023-05-03',
    title: 'Guardians of the Galaxy Vol. 3',
    video: false,
    vote_average: 7.998,
    vote_count: 5569
  },
  {
    adult: false,
    backdrop_path: '/1Kqp15MtZED7IVXFxNy9jXlX6xd.jpg',
    genre_ids: [ 27, 9648, 878 ],
    id: 1114205,
    original_language: 'ja',
    original_title: '忌怪島／きかいじま',
    overview: "Mysterious deaths befall on employees of a VR-tech company. There's an unprecedented fear waiting between reality and the virtual world.",
    popularity: 190.177,
    poster_path: '/5UA8qwDaCFCA2eyNafGZZQiKvSX.jpg',
    release_date: '2023-06-16',
    title: 'Immersion',
    video: false,
    vote_average: 6,
    vote_count: 5
  },
  {
    adult: false,
    backdrop_path: '/uOvcyJ3XmUv4geypGvZBeZEFMO6.jpg',
    genre_ids: [ 28, 80, 18 ],
    id: 945937,
    original_language: 'en',
    original_title: 'Fast Charlie',
    overview: 'When his aging mob boss is whacked, Charlie Swift, a loyal friend and hired gun, will stop at nothing to destroy the upcoming crew that took him out.',
    popularity: 201.182,
    poster_path: '/3y72ffwYRUPOj4yOQbiTaN897Tm.jpg',
    release_date: '2023-12-08',
    title: 'Fast Charlie',
    video: false,
    vote_average: 6.29,
    vote_count: 50
  },
  {
    adult: false,
    backdrop_path: '/rmfIhftLXpHEZzkLSpWQMZhirMJ.jpg',
    genre_ids: [ 35, 14 ],
    id: 823482,
    original_language: 'en',
    original_title: 'Dream Scenario',
    overview: 'Hapless family man Paul Matthews finds his life turned upside down when millions of strangers suddenly start seeing him in their dreams. But when his nighttime appearances take a nightmarish turn, Paul is forced to navigate his newfound stardom.',
    popularity: 232.689,
    poster_path: '/zhEaG0KQ32KerHEWmImsYLexDix.jpg',
    release_date: '2023-11-10',
    title: 'Dream Scenario',
    video: false,
    vote_average: 7.04,
    vote_count: 150
  },
  {
    adult: false,
    backdrop_path: '/hziiv14OpD73u9gAak4XDDfBKa2.jpg',
    genre_ids: [ 12, 14 ],
    id: 671,
    original_language: 'en',
    original_title: "Harry Potter and the Philosopher's Stone",
    overview: "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
    popularity: 232.949,
    poster_path: '/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
    release_date: '2001-11-16',
    title: "Harry Potter and the Philosopher's Stone",
    video: false,
    vote_average: 7.916,
    vote_count: 25839
  },
  {
    adult: false,
    backdrop_path: '/azD31DjpV3PJfjF3h72LVw2WCSD.jpg',
    genre_ids: [ 27 ],
    id: 807172,
    original_language: 'en',
    original_title: 'The Exorcist: Believer',
    overview: "When two girls disappear into the woods and return three days later with no memory of what happened to them, the father of one girl seeks out Chris MacNeil, who's been forever altered by what happened to her daughter fifty years ago.",
    popularity: 204.086,
    poster_path: '/qVKirUdmoex8SdfUk8WDDWwrcCh.jpg',
    release_date: '2023-10-04',
    title: 'The Exorcist: Believer',
    video: false,
    vote_average: 6.2,
    vote_count: 695
  },
  {
    adult: false,
    backdrop_path: '/cCIbJZVL3RQXp7CXohkAobhyNaw.jpg',
    genre_ids: [ 35 ],
    id: 1172029,
    original_language: 'es',
    original_title: 'Sobreviviendo mis XV',
    overview: 'Quinceañeras, a magical age... except when your family wants to put you in a bulky dress and make you waltz in front of everyone, which is exactly what happens to Danae shortly after she transfers to a very proper private school.  Now Danae has to manage to balance the demands of her family, those of her new friends and organize a cool, but traditional, but modern, but emotional, but aesthetic, but also grandmother-pleasing Quinceañera party... without dying in the process.',
    popularity: 198.059,
    poster_path: '/kr50u2w3G5L7RqLf6frFliJqPrZ.jpg',
    release_date: '2023-09-21',
    title: 'Sobreviviendo mis XV',
    video: false,
    vote_average: 7.527,
    vote_count: 55
  },
  {
    adult: false,
    backdrop_path: '/xvzxqKWltnj6qSiWBXRq6ZCdcrw.jpg',
    genre_ids: [ 53, 18 ],
    id: 1151534,
    original_language: 'es',
    original_title: 'Nowhere',
    overview: 'A young pregnant woman named Mia escapes from a country at war by hiding in a maritime container aboard a cargo ship. After a violent storm, Mia gives birth to the child while lost at sea, where she must fight to survive.',
    popularity: 194.626,
    poster_path: '/uldNFFKNXNvwss0MIZErMSFkBJZ.jpg',
    release_date: '2023-09-29',
    title: 'Nowhere',
    video: false,
    vote_average: 7.488,
    vote_count: 990
  },
  {
    adult: false,
    backdrop_path: '/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg',
    genre_ids: [ 12, 28, 878 ],
    id: 299536,
    original_language: 'en',
    original_title: 'Avengers: Infinity War',
    overview: 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
    popularity: 207.848,
    poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    release_date: '2018-04-25',
    title: 'Avengers: Infinity War',
    video: false,
    vote_average: 8.252,
    vote_count: 28161
  },
  {
    adult: false,
    backdrop_path: '/jkKVLzLWjSvTnc84VzeljhSy6j8.jpg',
    genre_ids: [ 10749, 18 ],
    id: 820525,
    original_language: 'en',
    original_title: 'After Everything',
    overview: 'Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.',
    popularity: 180.231,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    release_date: '2023-09-13',
    title: 'After Everything',
    video: false,
    vote_average: 6.986,
    vote_count: 608
  },
  {
    adult: false,
    backdrop_path: '/tFlSDoWQsAZ2qjICKzfP5Yw6zM5.jpg',
    genre_ids: [ 878, 12, 53 ],
    id: 131631,
    original_language: 'en',
    original_title: 'The Hunger Games: Mockingjay - Part 1',
    overview: 'Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.',
    popularity: 192.674,
    poster_path: '/4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg',
    release_date: '2014-11-19',
    title: 'The Hunger Games: Mockingjay - Part 1',
    video: false,
    vote_average: 6.805,
    vote_count: 15043
  },
  {
    adult: false,
    backdrop_path: '/m06dOSnShSmGfVgz4iSQhx6bzWv.jpg',
    genre_ids: [ 28, 12, 878 ],
    id: 775244,
    original_language: 'ar',
    original_title: 'موسى',
    overview: "An engineering college student invents the first of its kind robot in the Middle East, in an attempt to avenge his father's death and achieve justice, which gets him pursued by the authorities.",      
    popularity: 168.712,
    poster_path: '/8MO3nkwF8dbsz7dC5rGZuP3m3RS.jpg',
    release_date: '2021-08-11',
    title: 'Mousa',
    video: false,
    vote_average: 6.8,
    vote_count: 24
  },
  {
    adult: false,
    backdrop_path: '/7VEUOEfRzzrQfWddlIyLUKvh6Nf.jpg',
    genre_ids: [ 12, 10751, 14, 10749 ],
    id: 447277,
    original_language: 'en',
    original_title: 'The Little Mermaid',
    overview: 'The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.',
    popularity: 197.878,
    poster_path: '/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg',
    release_date: '2023-05-18',
    title: 'The Little Mermaid',
    video: false,
    vote_average: 6.454,
    vote_count: 2479
  },
  {
    adult: false,
    backdrop_path: '/tVIzzMLT9pye5BWNwHovBleruNS.jpg',
    genre_ids: [ 28 ],
    id: 662167,
    original_language: 'en',
    original_title: 'Agent Jade Black',
    overview: 'A skilled young female agent is tasked with capturing a rogue former agent before she can unleash a biological weapon starting with the wealthy and powerful purveyors of the international sex trade.', 
    popularity: 173.434,
    poster_path: '/wGHaEtBz6AXqGVooaADB1tlyjBp.jpg',
    release_date: '2020-09-29',
    title: 'Agent Jade Black',
    video: false,
    vote_average: 2,
    vote_count: 4
  },
  {
    adult: false,
    backdrop_path: '/wurJckmxIzn2GrJcPDuNFFy1gWx.jpg',
    genre_ids: [ 878 ],
    id: 920258,
    original_language: 'en',
    original_title: 'The Immortal Wars: Rebirth',
    overview: 'Rebirth takes place during the early brutal stages of Dominion Industries. In this story watch Olive and other deviants undergo a series of deadly experiments lead by Laurie Harvey and her team.',     
    popularity: 178.474,
    poster_path: '/sp0fISNTyzttKfE0PB4ObG5ZRzC.jpg',
    release_date: '2021-11-02',
    title: 'The Immortal Wars: Rebirth',
    video: false,
    vote_average: 3.5,
    vote_count: 2
  },
  
  {
    adult: false,
    backdrop_path: '/jSju0YPx50ZmemYLsayK1PS9dF0.jpg',
    genre_ids: [ 53, 14, 27 ],
    id: 1017794,
    original_language: 'zh',
    original_title: '深海蛇难',
    overview: 'After his fiancé sudden death, Qin Yu is convinced Cass Corporation is somehow involved and is determined to find the truth. Booking passage on the same cruise ship as former Cass employee, Jason, Qin Yu follows him. Qin Yu hopes to secure the information he needs on Cass to be able to testify against them in court. But Qin Yu isn’t the only person on board hoping to gain intel on Cass. Desperate for a story, reporter Feng Li tails both Qin Yu and Jason, booking passage on the same cruise. Unfortunately, no one has much of a chance to gain information as the ship is suddenly attacked by giant mutant snakes. Escaping the attack, the survivors find themselves on the very island Cass Corporation has been conducting their illegal experiments. Hunted by monsters of all sorts, will any of the survivors find a way to bring Cass down and make it off the island alive?',
    popularity: 201.445,
    poster_path: '/t5eBA5cmn0hUOVfXgZNMU4bzVNt.jpg',
    release_date: '2022-08-27',
    title: 'Deep Sea Mutant Snake',
    video: false,
    vote_average: 7,
    vote_count: 17
  },
  {
    adult: false,
    backdrop_path: '/bSvUW4JQ6g4QiKvwejcfcPRd4Ke.jpg',
    genre_ids: [ 12, 35, 10751, 14 ],
    id: 118,
    original_language: 'en',
    original_title: 'Charlie and the Chocolate Factory',
    overview: "A young boy wins a tour through the most magnificent chocolate factory in the world, led by the world's most unusual candy maker.",
    popularity: 201.427,
    poster_path: '/wfGfxtBkhBzQfOZw4S8IQZgrH0a.jpg',
    release_date: '2005-07-13',
    title: 'Charlie and the Chocolate Factory',
    video: false,
    vote_average: 7.048,
    vote_count: 14266
  },
  {
    adult: false,
    backdrop_path: '/vRx6kzCItpqwnYCcj2z8qf70gv3.jpg',
    genre_ids: [ 28, 18, 10749 ],
    id: 10908,
    original_language: 'en',
    original_title: 'Inferno',
    overview: 'Eddie Lomax (Jean-Claude Van Damme) is a drifter who has been in a suicidal funk since the death of his close friend Johnny (Danny Trejo). Riding his motorcycle into a small desert town where Johnny once lived, Lomax is confronted by a gang of toughs, who beat him and steal his bike. However, Lomax is not a man to take an injustice lying down, and soon he begins exacting a violent revenge on the men who stole his motorcycle, with local handyman Jubal Early (Pat Morita) lending a hand and several area ladies offering aid and comfort.',
    popularity: 198.38,
    poster_path: '/dFlI0Vb4JOsRXG1JSS2Ufs6Sp8k.jpg',
    release_date: '1999-09-25',
    title: 'Inferno',
    video: false,
    vote_average: 6.1,
    vote_count: 284
  },
  {
    adult: false,
    backdrop_path: '/S3EIcOUQYxgd3QzjOo2rZJ2MN8.jpg',
    genre_ids: [ 28, 18, 10752 ],
    id: 554600,
    original_language: 'hi',
    original_title: 'Uri: The Surgical Strike',
    overview: 'Following the roguish terrorist attacks at Uri Army Base camp in Kashmir, India takes the fight to the enemy, in its most successful covert operation till date with one and only one objective of avenging their fallen heroes.',
    popularity: 198.153,
    poster_path: '/yNySAgpAnWmPpYinim9E0tUzJWG.jpg',
    release_date: '2019-01-11',
    title: 'Uri: The Surgical Strike',
    video: false,
    vote_average: 7.151,
    vote_count: 327
  },
  {
    adult: false,
    backdrop_path: '/3xvdNyZ9WsVJpyeGhm85fukeZz4.jpg',
    genre_ids: [ 878, 9648, 53 ],
    id: 1001835,
    original_language: 'en',
    original_title: 'Wifelike',
    overview: 'A grieving detective in the near-future hunts down criminals who trade artificial humans on the black market. In the fight to end AI exploitation, an underground resistance attempts to infiltrate him by sabotaging the programming of the artificial human assigned as his companion to behave like his late wife. She begins to question her reality as memories of a past life begin to surface in a world where nothing is as it seems.',
    popularity: 196.437,
    poster_path: '/tea2gDZPxw0wfKC2S2VRWHagtt4.jpg',
    release_date: '2022-08-12',
    title: 'Wifelike',
    video: false,
    vote_average: 6.976,
    vote_count: 210
  },
  {
    adult: false,
    backdrop_path: '/lyHmhoRj3zXSdeCYbs2oOXLCF4K.jpg',
    genre_ids: [ 16, 12, 10751, 14 ],
    id: 459003,
    original_language: 'uk',
    original_title: 'Мавка: Лісова пісня',
    overview: 'Forest soul Mavka faces an impossible choice between her heart and her duty as guardian to the Heart of the Forest, when she falls in love with the talented young human musician Lukas.',
    popularity: 193.242,
    poster_path: '/eeJjd9JU2Mdj9d7nWRFLWlrcExi.jpg',
    release_date: '2023-03-02',
    title: 'Mavka: The Forest Song',
    video: false,
    vote_average: 7.3,
    vote_count: 559
  },
  {
    adult: false,
    backdrop_path: '/5rrGVmRUuCKVbqUu41XIWTXJmNA.jpg',
    genre_ids: [ 12, 14 ],
    id: 674,
    original_language: 'en',
    original_title: 'Harry Potter and the Goblet of Fire',
    overview: "When Harry Potter's name emerges from the Goblet of Fire, he becomes a competitor in a grueling battle for glory among three wizarding schools—the Triwizard Tournament. But since Harry never submitted his name for the Tournament, who did? Now Harry must confront a deadly dragon, fierce water demons and an enchanted maze only to find himself in the cruel grasp of He Who Must Not Be Named.",
    popularity: 193.082,
    poster_path: '/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg',
    release_date: '2005-11-16',
    title: 'Harry Potter and the Goblet of Fire',
    video: false,
    vote_average: 7.814,
    vote_count: 19611
  },
  {
    adult: false,
    backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    genre_ids: [ 12, 18, 878 ],
    id: 157336,
    original_language: 'en',
    original_title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', 
    popularity: 189.976,
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    release_date: '2014-11-05',
    title: 'Interstellar',
    video: false,
    vote_average: 8.423,
    vote_count: 33202
  },
  {
    adult: false,
    backdrop_path: '/e1nCA9fswMsNdkdaCkVjdbcGmuG.jpg',
    genre_ids: [ 16, 10751, 14 ],
    id: 88212,
    original_language: 'en',
    original_title: 'Prep & Landing Stocking Stuffer: Operation: Secret Santa',
    overview: 'Wayne and Lanny, now partners, are called by Magee to meet with a secret contact – Mrs. Claus, who sends them on a new mission to retrieve a box from Santa’s secret workshop. Later they sneak into Santa’s office while he is asleep, using their high tech equipment from the previous film. Lanny’s expertise at dressing the tree enables them to enter the hidden workshop where they recover the box and escape just in time. But what is the box for?',
    popularity: 189.079,
    poster_path: '/9BCphvFuTMO1CkNXslrUmEZ4imh.jpg',
    release_date: '2010-12-07',
    title: 'Prep & Landing Stocking Stuffer: Operation: Secret Santa',
    video: false,
    vote_average: 6.5,
    vote_count: 99
  },
  {
    adult: false,
    backdrop_path: '/ruL3QwqSRXOgzr1kn23CnRFRqbt.jpg',
    genre_ids: [ 27 ],
    id: 638238,
    original_language: 'tl',
    original_title: 'Sunod',
    overview: "A woman is desperate to find the cure to her daughter's illness. She takes a job at a call center, only to be haunted by the ghost in it.",
    popularity: 188.899,
    poster_path: '/e0tLQDrblZQ1NfbwNdDScc9Ndu6.jpg',
    release_date: '2019-12-25',
    title: 'Sunod',
    video: false,
    vote_average: 6.526,
    vote_count: 19
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 99 ],
    id: 1206029,
    original_language: 'es',
    original_title: 'Muchachos, la película de la gente',
    overview: '',
    popularity: 186.899,
    poster_path: '/4lb7Lpwzu908fbph9enKN0axiYy.jpg',
    release_date: '2023-12-07',
    title: 'Muchachos, la película de la gente',
    video: false,
    vote_average: 6.25,
    vote_count: 4
  },
  {
    adult: false,
    backdrop_path: '/1stUIsjawROZxjiCMtqqXqgfZWC.jpg',
    genre_ids: [ 12, 14 ],
    id: 672,
    original_language: 'en',
    original_title: 'Harry Potter and the Chamber of Secrets',
    overview: 'Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.',
    popularity: 184.923,
    poster_path: '/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg',
    release_date: '2002-11-13',
    title: 'Harry Potter and the Chamber of Secrets',
    video: false,
    vote_average: 7.719,
    vote_count: 20764
  },
  {
    adult: false,
    backdrop_path: '/vQpvNDc0AFao8BbWyXDFVVrqiZj.jpg',
    genre_ids: [ 27 ],
    id: 853387,
    original_language: 'en',
    original_title: 'Lord of Misrule',
    overview: "When the daughter of the town's new priest goes missing during the harvest festival, a desperate search begins, uncovering the town's dark history and resurfacing tales of a mysterious, malevolent spirit that demands sacrifice.",
    popularity: 184.323,
    poster_path: '/eCNJuGsCNdf2yf4F3UcDg1WZTbo.jpg',
    release_date: '2023-10-26',
    title: 'Lord of Misrule',
    video: false,
    vote_average: 6,
    vote_count: 3
  },
  {
    adult: false,
    backdrop_path: '/eSsMzJpzAwCa69tm6Wco2il44aJ.jpg',
    genre_ids: [ 28, 80, 18, 53 ],
    id: 939335,
    original_language: 'en',
    original_title: 'Muzzle',
    overview: 'LAPD K-9 officer Jake Rosser has just witnessed the shocking murder of his dedicated partner by a mysterious assailant. As he investigates the shooter’s identity, he uncovers a vast conspiracy that has a chokehold on the city in this thrilling journey through the tangled streets of Los Angeles and the corrupt bureaucracy of the LAPD.',
    popularity: 183.867,
    poster_path: '/qXChf7MFL36BgoLkiB3BzXiwW82.jpg',
    release_date: '2023-09-29',
    title: 'Muzzle',
    video: false,
    vote_average: 6.593,
    vote_count: 134
  },
  {
    adult: false,
    backdrop_path: '/xIv4HuvPP9nL7PU9vq2PKOKFvhj.jpg',
    genre_ids: [ 28, 16 ],
    id: 116776,
    original_language: 'ja',
    original_title: 'ドラゴンボール 魔訶不思議大冒険',
    overview: "Master Roshi has succeeded at the one mission he valued most: to train Goku and Krillin to become ultimate fighters. So, he arranges for them to test their mettle at a competition hosted by Emperor Chiaotzu. Not everyone's playing by the rules, however, as a member of the ruler's household schemes to use the Dragonballs to extort money and power from the royal.",
    popularity: 183.865,
    poster_path: '/5aXG0B3TYTpQsodXzvYCkKQfpB1.jpg',
    release_date: '1988-07-09',
    title: 'Dragon Ball: Mystical Adventure',
    video: false,
    vote_average: 6.8,
    vote_count: 231
  },
  {
    adult: false,
    backdrop_path: '/sp6egj5NHHRGmCMdIoTNdbLwACR.jpg',
    genre_ids: [ 35, 14, 10751 ],
    id: 1022964,
    original_language: 'en',
    original_title: 'Candy Cane Lane',
    overview: "A man, determined to win the neighborhood's annual Christmas decorating contest, makes a pact with an elf to help him win. However, the elf casts a spell bringing the twelve days of Christmas to life, bringing chaos to the small, unsuspecting town.",
    popularity: 181.571,
    poster_path: '/of6Ds591FJTKoBHYjDFzH6jlTyK.jpg',
    release_date: '2023-11-29',
    title: 'Candy Cane Lane',
    video: false,
    vote_average: 6.197,
    vote_count: 271
  },
  {
    adult: false,
    backdrop_path: '/d1RHScaZc7I8j0lDke1c4AxI435.jpg',
    genre_ids: [ 28, 12, 16, 10751, 35 ],
    id: 9502,
    original_language: 'en',
    original_title: 'Kung Fu Panda',
    overview: `When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the "chosen one" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won't be easy. It's up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.`,
    popularity: 181.195,
    poster_path: '/wWt4JYXTg5Wr3xBW2phBrMKgp3x.jpg',
    release_date: '2008-06-04',
    title: 'Kung Fu Panda',
    video: false,
    vote_average: 7.254,
    vote_count: 10725
  },
  {
    adult: false,
    backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
    genre_ids: [ 28, 12, 878 ],
    id: 436270,
    original_language: 'en',
    original_title: 'Black Adam',
    overview: 'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
    popularity: 180.313,
    poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
    release_date: '2022-10-19',
    title: 'Black Adam',
    video: false,
    vote_average: 6.988,
    vote_count: 5695
  },
  {
    adult: false,
    backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    genre_ids: [ 18, 28, 80, 53 ],
    id: 155,
    original_language: 'en',
    original_title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    popularity: 179.031,
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    release_date: '2008-07-16',
    title: 'The Dark Knight',
    video: false,
    vote_average: 8.513,
    vote_count: 31138
  },
  {
    adult: false,
    backdrop_path: '/gE1AlXZWgUTj4rRCImsvuLXVa59.jpg',
    genre_ids: [ 10751, 14, 35 ],
    id: 811050,
    original_language: 'it',
    original_title: 'La befana vien di notte 2 - Le origini',
    overview: '18th century. Paola, a young, reckless street urchin inadvertently gets in the way of the plans of terrifying Baron De Michelis, a small and mean hunchback always escorted by his trusted (and abused) minion Marmotta, with an unquenchable thirst for power and an unmeasurable hate for witches. The intervention of the sweet and powerful Dolores, a good witch who has devoted her life to children, saves Paola from being burned at the stake. Through a magical apprenticeship, breakneck pursuits, incredible transformations and a whole lot of trouble, Paola will discover that fate has something really special in store for her… And so the legend begins.',
    popularity: 178.845,
    poster_path: '/b2Yv544mACPTcp8ZrfIaLOcQXj6.jpg',
    release_date: '2021-12-30',
    title: 'The Legend of the Christmas Witch: The Origins',
    video: false,
    vote_average: 6.229,
    vote_count: 59
  },
  {
    adult: false,
    backdrop_path: '/15BnuDQ8pYRmLqPZKAk5vIhUu9J.jpg',
    genre_ids: [ 37, 53, 28 ],
    id: 843380,
    original_language: 'en',
    original_title: 'Dead for a Dollar',
    overview: 'In 1897, veteran bounty hunter Max Borlund is deep into Mexico where he encounters professional gambler and outlaw Joe Cribbens — a sworn enemy he sent to prison years before. Max is on a mission to find and return Rachel Kidd, the wife of a wealthy businessman, who as the story is told to Max, has been abducted by Buffalo Soldier Elijah Jones. Max is ultimately faced with a showdown to save honor.',
    popularity: 250.302,
    poster_path: '/1AnXfjxFqMsQmUPSvt9YxUJhfFw.jpg',
    release_date: '2022-09-30',
    title: 'Dead for a Dollar',
    video: false,
    vote_average: 5.613,
    vote_count: 164
  },
  {
    adult: false,
    backdrop_path: '/obKmfNexgL4ZP5cAmzdL4KbHHYX.jpg',
    genre_ids: [ 12, 14 ],
    id: 673,
    original_language: 'en',
    original_title: 'Harry Potter and the Prisoner of Azkaban',
    overview: 'Year three at Hogwarts means new fun and challenges as Harry learns the delicate art of approaching a Hippogriff, transforming shape-shifting Boggarts into hilarity and even turning back time. But the term also brings danger: soul-sucking Dementors hover over the school, an ally of the accursed He-Who-Cannot-Be-Named lurks within the castle walls, and fearsome wizard Sirius Black escapes Azkaban. And Harry will confront them all.',
    popularity: 172.484,
    poster_path: '/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg',
    release_date: '2004-05-31',
    title: 'Harry Potter and the Prisoner of Azkaban',
    video: false,
    vote_average: 8.02,
    vote_count: 20387
  },
  {
    adult: false,
    backdrop_path: '/idfNNlVwjVkBQrM2eWpLZiDOTIc.jpg',
    genre_ids: [ 10751, 14, 35 ],
    id: 252,
    original_language: 'en',
    original_title: 'Willy Wonka & the Chocolate Factory',
    overview: 'When eccentric candy man Willy Wonka promises a lifetime supply of sweets and a tour of his chocolate factory to five lucky kids, penniless Charlie Bucket seeks the golden ticket that will make him a winner.',
    popularity: 168.506,
    poster_path: '/vmpsZkrs4Uvkp9r1atL8B3frA63.jpg',
    release_date: '1971-06-29',
    title: 'Willy Wonka & the Chocolate Factory',
    video: false,
    vote_average: 7.487,
    vote_count: 3220
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 27, 28, 35 ],
    id: 972731,
    original_language: 'en',
    original_title: '2025: Blood, White & Blue',
    overview: 'Undercover U.S. agent Bill Wilson makes the bust of his career taking down a cartel leader. Hiding the evidence in his home exposes his family to a brutal targeting on the night of the annual Purge, the deadliest night of the year.',
    popularity: 155.049,
    poster_path: '/1S9pjiZejBiSVV88qU59ifZ7q0N.jpg',
    release_date: '2022-07-01',
    title: '2025: Blood, White & Blue',
    video: false,
    vote_average: 5,
    vote_count: 3
  },
  {
    adult: false,
    backdrop_path: '/p9DKeXp6FPJtAQ1k13Z4zPWrCbN.jpg',
    genre_ids: [ 18 ],
    id: 1058694,
    original_language: 'en',
    original_title: 'Radical',
    overview: 'In a Mexican border town plagued by neglect, corruption, and violence, a frustrated teacher tries a radical new method to break through his students’ apathy and unlock their curiosity, their potential… and maybe even their genius.',
    popularity: 152.305,
    poster_path: '/eSatbygYZp8ooprBHZdb6GFZxGB.jpg',
    release_date: '2023-10-19',
    title: 'Radical',
    video: false,
    vote_average: 7.6,
    vote_count: 13
  },
  {
    adult: false,
    backdrop_path: '/by7XJXrMGKIhV2fbQm9QRDfJxxI.jpg',
    genre_ids: [ 878, 28, 53 ],
    id: 845844,
    original_language: 'en',
    original_title: 'Extraction Point',
    overview: 'An alien visitor must race against time to reach his extraction point after his UFO is forced to crash down on Earth.',
    popularity: 136.995,
    poster_path: '/1djkxHjE3Z2Wk30nrIYm3tj19DO.jpg',
    release_date: '2021-06-29',
    title: 'Extraction Point',
    video: false,
    vote_average: 5.432,
    vote_count: 37
  },
  {
    adult: false,
    backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
    genre_ids: [ 28, 12, 878 ],
    id: 505642,
    original_language: 'en',
    original_title: 'Black Panther: Wakanda Forever',
    overview: 'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
    popularity: 174.103,
    poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
    release_date: '2022-11-09',
    title: 'Black Panther: Wakanda Forever',
    video: false,
    vote_average: 7.16,
    vote_count: 5754
  },
  {
    adult: false,
    backdrop_path: '/8FWC4tDWB1p006vwiubhai4a8iS.jpg',
    genre_ids: [ 10751, 12, 14 ],
    id: 1020969,
    original_language: 'no',
    original_title: 'Teddybjørnens Jul',
    overview: "Christmas peace falls over the small town, but at the Christmas market there's hectic activity. Mariann discovers a teddy bear at the top shelf. Is he alive? Mariann must get the teddy whatsoever. But Teddy wants to get to a rich family.",
    popularity: 242.06,
    poster_path: '/jEf96axaZhZQEu9ORVtEujBTG9p.jpg',
    release_date: '2022-11-05',
    title: "Teddy's Christmas",
    video: false,
    vote_average: 7.4,
    vote_count: 22
  },
  {
    adult: false,
    backdrop_path: '/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
    genre_ids: [ 28, 18 ],
    id: 361743,
    original_language: 'en',
    original_title: 'Top Gun: Maverick',
    overview: 'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
    popularity: 168.3,
    poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    release_date: '2022-05-24',
    title: 'Top Gun: Maverick',
    video: false,
    vote_average: 8.241,
    vote_count: 7952
  },
  {
    adult: false,
    backdrop_path: '/LfUXJQOhBa0cfQsGnYwuSUaHId.jpg',
    genre_ids: [ 37 ],
    id: 940175,
    original_language: 'en',
    original_title: 'A Tale of Two Guns',
    overview: 'In the lawless West, The Cowboys, a notorious brotherhood of killers and thieves, reigned over the land with brutal fists and fast guns. Fate had finally caught up with them and now the merciless gang has but a single surviving member. When a deputized gunslinger takes up the call to hunt down the last Cowboy, the chase is on and the bullets fly, and only one of these hardened men can survive.',
    popularity: 146.585,
    poster_path: '/kT3Zy7kOQERHnpEHT1wMwXEpJsk.jpg',
    release_date: '2022-02-17',
    title: 'A Tale of Two Guns',
    video: false,
    vote_average: 6.271,
    vote_count: 24
  },
  {
    adult: false,
    backdrop_path: '/a0GM57AnJtNi7lMOCamniiyV10W.jpg',
    genre_ids: [ 16, 12, 14, 18 ],
    id: 508883,
    original_language: 'ja',
    original_title: '君たちはどう生きるか',
    overview: `While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the "long-awaited one."`,
    popularity: 191.126,
    poster_path: '/jDQPkgzerGophKRRn7MKm071vCU.jpg',
    release_date: '2023-07-14',
    title: 'The Boy and the Heron',
    video: false,
    vote_average: 7.241,
    vote_count: 318
  },
  {
    adult: false,
    backdrop_path: '/sRvXNDItGlWCqtO3j6wks52FmbD.jpg',
    genre_ids: [ 16, 35, 14, 12, 10751 ],
    id: 808,
    original_language: 'en',
    original_title: 'Shrek',
    overview: "It ain't easy bein' green -- especially if you're a likable (albeit smelly) ogre named Shrek. On a mission to retrieve a gorgeous princess from the clutches of a fire-breathing dragon, Shrek teams up with an unlikely compatriot -- a wisecracking donkey.",
    popularity: 177.224,
    poster_path: '/dyhaB19AICF7TO7CK2aD6KfymnQ.jpg',
    release_date: '2001-05-18',
    title: 'Shrek',
    video: false,
    vote_average: 7.732,
    vote_count: 16071
  },
  {
    adult: false,
    backdrop_path: '/28er4p7B5zMSxUDQKPF1hBsgnys.jpg',
    genre_ids: [ 28, 12, 53 ],
    id: 872906,
    original_language: 'hi',
    original_title: 'जवान',
    overview: 'An emotional journey of a prison warden, driven by a personal vendetta while keeping up to a promise made years ago, recruits inmates to commit outrageous crimes that shed light on corruption and injustice, in an attempt to get even with his past,  and that leads him to an unexpected reunion.',
    popularity: 159.844,
    poster_path: '/qh2lLZ5HtLYPxxuS7ccxMhwgEn6.jpg',
    release_date: '2023-09-07',
    title: 'Jawan',
    video: false,
    vote_average: 7.334,
    vote_count: 157
  },
  {
    adult: false,
    backdrop_path: '/EEASOZj5Mm2u6G3K4HS4pKIlfC.jpg',
    genre_ids: [ 27, 9648 ],
    id: 1035982,
    original_language: 'en',
    original_title: 'Hell House LLC Origins: The Carmichael Manor',
    overview: 'A group of cold case investigators stay at the Carmichael Manor, site of the grisly and unsolved murders of the Carmichael family back in the eighties. After four nights, the group was never heard from again. What is discovered on their footage is even more disturbing than anything found on the Hell House tapes.',
    popularity: 157.702,
    poster_path: '/9YlsIwWATGwT6LL5UZVF5xoBTcC.jpg',
    release_date: '2023-10-24',
    title: 'Hell House LLC Origins: The Carmichael Manor',
    video: false,
    vote_average: 6.298,
    vote_count: 47
  },
  {
    adult: false,
    backdrop_path: '/wmeNorZYUd0QCxzOXqIYsVuYpbF.jpg',
    genre_ids: [ 35, 12, 28 ],
    id: 849236,
    original_language: 'ru',
    original_title: 'Бендер: Золото Империи',
    overview: 'The hunt for imperial gold continues. A priceless scepter, a treasure that could secure a worry-free life in sunny Rio de Janeiro for Ibrahim Bender and his young apprentice Ostap, has slipped from under their noses and ended up in possession of Nestor Makhno, an anarchist army commander. Makhno is convinced that the scepter is one of many imperial relics hidden in the area. With mafia, partisans, and officers of the Red and White armies all determined to get their hands on the fabled gold cache, Ostap and his mentor Ibrahim must surpass their own brilliance to outmaneuver their rivals and snatch the prize. And with Ostap’s beloved fair maiden losing her trust in him, he must do everything in his power to win her back and stop her from marrying another man.',
    popularity: 234.464,
    poster_path: '/yDpfHMnj6MvJYcaSUPFkeI0IKc0.jpg',
    release_date: '2021-07-15',
    title: "Ostap Bender. The Empire's Gold",
    video: false,
    vote_average: 6.1,
    vote_count: 33
  },
  {
    adult: false,
    backdrop_path: '/AjDyXDvk4VOtDp9aLJpAnBx1uyD.jpg',
    genre_ids: [ 28, 12, 878, 53 ],
    id: 9381,
    original_language: 'en',
    original_title: 'Babylon A.D.',
    overview: 'A veteran-turned-mercenary is hired to take a young woman with a secret from post-apocalyptic Eastern Europe to New York City.',
    popularity: 152.612,
    poster_path: '/kt9nqD0uOar8IVE9191HXhWOXKI.jpg',
    release_date: '2008-08-20',
    title: 'Babylon A.D.',
    video: false,
    vote_average: 5.642,
    vote_count: 1953
  },
  {
    adult: false,
    backdrop_path: '/9eAn20y26wtB3aet7w9lHjuSgZ3.jpg',
    genre_ids: [ 12, 28, 878 ],
    id: 507086,
    original_language: 'en',
    original_title: 'Jurassic World Dominion',
    overview: "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators ona planet they now share with history's most fearsome creatures.", 
    popularity: 141.3,
    poster_path: '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg',
    release_date: '2022-06-01',
    title: 'Jurassic World Dominion',
    video: false,
    vote_average: 6.755,
    vote_count: 5433
  },
  {
    adult: false,
    backdrop_path: '/pkxPkHOPJjOvzfQOclANEBT8OfK.jpg',
    genre_ids: [ 12, 14 ],
    id: 675,
    original_language: 'en',
    original_title: 'Harry Potter and the Order of the Phoenix',
    overview: 'Returning for his fifth year of study at Hogwarts, Harry is stunned to find that his warnings about the return of Lord Voldemort have been ignored. Left with no choice, Harry takes matters into his own hands, training a small group of students to defend themselves against the dark arts.',
    popularity: 153.915,
    poster_path: '/5aOyriWkPec0zUDxmHFP9qMmBaj.jpg',
    release_date: '2007-07-08',
    title: 'Harry Potter and the Order of the Phoenix',
    video: false,
    vote_average: 7.684,
    vote_count: 18471
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 18, 10749 ],
    id: 1156593,
    original_language: 'es',
    original_title: 'Culpa tuya',
    overview: '',
    popularity: 139.055,
    poster_path: '/3pkjbiL9ju2VdLohIGW4NOYkASi.jpg',
    release_date: '',
    title: 'Your Fault',
    video: false,
    vote_average: 0,
    vote_count: 0
  },
  {
    adult: false,
    backdrop_path: '/a3AzYS2JiZ9GdHiAxDTmIajKgH0.jpg',
    genre_ids: [ 28, 878, 12 ],
    id: 823464,
    original_language: 'en',
    original_title: 'Godzilla x Kong: The New Empire',
    overview: 'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
    popularity: 161.504,
    poster_path: '/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg',
    release_date: '2024-04-10',
    title: 'Godzilla x Kong: The New Empire',
    video: false,
    vote_average: 0,
    vote_count: 0
  }

];
